---
name: citm-example-gw
services:
  cert-maker:
    build:
      context: ../../shared-certificates
      dockerfile: Dockerfile
    volumes:
      - ../../shared-certificates:/shared-certificates
    command:
      - /bin/bash
      - /shared-certificates/mk-devcerts.sh
  citm:
    build:
      context: ../..
      dockerfile: Dockerfile
    depends_on:
      cert-maker:
        condition: service_completed_successfully
    volumes:
      - ./caddy-conf.d:/etc/caddy/conf.d:ro
      - ../../shared-certificates/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'
      - '127.0.0.1:443:443/udp'
    networks:
      - citm-example

networks:
  citm-example:
    external: true
