---
name: citm-example-gw
services:
  cert-maker:
    build:
      context: ../../shared-certificates
      dockerfile: Dockerfile
    command:
      - /bin/bash
      - /shared-certificates/mk-devcerts.sh
    volumes:
      - ../../shared-certificates:/shared-certificates
  citm:
    build:
      context: ../..
      dockerfile: Dockerfile
    depends_on:
      cert-maker:
        condition: service_completed_successfully
    networks:
      - citm-example
    volumes:
      - ./caddy-conf.d:/etc/caddy/conf.d:ro
      - ../../shared-certificates/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

networks:
  citm-example:
    external: true
