name: citm-mk-devcerts
services:
  maker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/shared-certificates
    command:
      - /bin/bash
      - /shared-certificates/mk-devcerts.sh
