---
name: citm-example-service1
services:
  cert-maker:
    build:
      context: ../../shared-certificates
      dockerfile: Dockerfile
    volumes:
      - ../../shared-certificates:/shared-certificates
    command:
      - /bin/bash
      - /shared-certificates/mk-devcerts.sh
  citm:
    build:
      context: ../..
      dockerfile: Dockerfile
    depends_on:
      cert-maker:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./caddy-conf.d:/etc/caddy/conf.d:ro
      - ./citm-mocks:/citm-mocks:ro
      - ../../shared-certificates/certs:/certs:ro
    environment:
      - MOCK_PATHS=/citm-mocks/**/*.mako
    networks:
      - citm-example
    labels:
      - citm_network=citm-example
      - citm_dns_names=service1.internal,alt-service1.internal
  service1:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      cert-maker:
        condition: service_completed_successfully
    volumes:
      - ../../shared-certificates/certs:/certs:ro
    network_mode: service:citm
    init: true
networks:
  citm-example:
    external: true
