[project]
name = "citm-utils"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "docker>=7.1.0",
    "flask>=3.1.2",
    "gunicorn>=25.1.0",
    "pip-system-certs>=5.3",
    "requests>=2.32.5",
]
