---
name: citm-development-container

services:
  cert-maker:
    build:
      context: ../shared-certificates
      dockerfile: Dockerfile
    volumes:
      - ../shared-certificates:/shared-certificates
    command:
      - /bin/bash
      - /shared-certificates/mk-devcerts.sh
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        DEVCONTAINER: true
    depends_on:
      cert-maker:
        condition: service_completed_successfully
    volumes:
      - vscode-server-data:/home/dev/.vscode-server
      - ../shared-certificates/certs:/certs:ro
      - ../example/gw/caddy-conf.d:/etc/caddy/conf.d:ro
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - ..:/workspace:cached
    environment:
      - DOCKER_HOST=tcp://localhost:2375
    ports:
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'
      - '127.0.0.1:443:443/udp'
      - '127.0.0.1:3858:3858'
    networks:
      - citm-example
    command: /start-supervisord
    init: true
    tty: true
  docker-socket-proxy:
    image: alpine/socat:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: service:devcontainer
    command:
      - TCP-LISTEN:2375,fork,reuseaddr
      - UNIX-CONNECT:/var/run/docker.sock

networks:
  citm-example:
    external: true

volumes:
  vscode-server-data:
    driver: local
