---
name: citm-development-container

services:
  cert-maker:
    build:
      context: ../shared-certificates
      dockerfile: Dockerfile
    volumes:
      - ../shared-certificates:/shared-certificates
    command:
      - /bin/bash
      - /shared-certificates/mk-devcerts.sh
  devcontainer:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        DEVCONTAINER: true
    depends_on:
      cert-maker:
        condition: service_completed_successfully
    volumes:
      - vscode-server-data:/home/dev/.vscode-server
      - ../shared-certificates/certs:/certs:ro
      - ../example/gw/caddy-conf.d:/etc/caddy/conf.d:ro
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - ..:/workspace:cached
    environment:
      - DOCKER_HOST=tcp://localhost:2375
    ports:
      - '0.0.0.0:${CITM_ADMIN_PORT:-3858}:3858'
      - '0.0.0.0:${CITM_HTTP_PORT:-80}:80'
      - '0.0.0.0:${CITM_HTTP_PROXY_PORT:-8380}:8380'
      - '0.0.0.0:${CITM_HTTPS_PORT:-443}:443/udp'
      - '0.0.0.0:${CITM_HTTPS_PORT:-443}:443'
      - '0.0.0.0:${CITM_SOCKS5_PROXY_PORT:-8381}:8381'
    networks:
      - citm-example
    command: /start-supervisord
    init: true
    tty: true
  docker-socket-proxy:
    image: alpine/socat:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: service:devcontainer
    command:
      - TCP-LISTEN:2375,fork,reuseaddr
      - UNIX-CONNECT:/var/run/docker.sock

networks:
  citm-example:
    external: true

volumes:
  vscode-server-data:
    driver: local
