name: Docker Publish

on:
  release:
    types: [published]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: index.docker.io
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/citm
      TAG: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@main
      - name: Set up Docker
        uses: docker/setup-docker-action@master
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        id: push
        uses: docker/build-push-action@master
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
          context: .
          file: Dockerfile
          push: true
          tags: "${{ env.IMAGE }}:${{ env.TAG }},${{ env.IMAGE }}:latest"
      - name: Attest
        uses: actions/attest-build-provenance@main
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
